# Route pour créer un nouveau véhicule
vehicle_create:
    path: '/api/vehicles'
    controller: App\Controller\VehicleController::createVehicle
    methods: ['POST']

# Route pour mettre à jour un véhicule existant
vehicle_update:
    path: '/api/vehicles/{id}'
    controller: App\Controller\VehicleController::updateVehicle
    methods: ['PUT']

# Route pour supprimer un véhicule
vehicle_delete:
    path: '/api/vehicles/{id}'
    controller: App\Controller\VehicleController::deleteVehicle
    methods: ['DELETE']

# Route pour récupérer tous les véhicules
vehicle_index:
    path: '/api/vehicles'
    controller: App\Controller\VehicleController::getAllVehicles
    methods: ['GET']

# Route pour récupérer un véhicule spécifique
vehicle_get:
    path: '/api/vehicles/{id}'
    controller: App\Controller\VehicleController::getVehicle
    methods: ['GET']

# Route pour créer une nouvelle disponibilité
availability_create:
    path: '/api/availabilities'
    controller: App\Controller\AvailabilityController::createAvailability
    methods: ['POST']

# Route pour mettre à jour une disponibilité existante
availability_update:
    path: '/api/availabilities/{id}'
    controller: App\Controller\AvailabilityController::updateAvailability
    methods: ['PUT']

# Route pour supprimer une disponibilité
availability_delete:
    path: '/api/availabilities/{id}'
    controller: App\Controller\AvailabilityController::deleteAvailability
    methods: ['DELETE']

# Route pour récupérer une disponibilité spécifique
availability_show:
    path: '/api/availabilities/{id}'
    controller: App\Controller\AvailabilityController::show
    methods: ['GET']

# Route pour récupérer les disponibilités d'un véhicule spécifique
availability_get_by_vehicle:
    path: '/api/availabilities/vehicle/{id}'
    controller: App\Controller\AvailabilityController::getAvailabilitiesByVehicle
    methods: ['GET']
